### ISSUE TITLE
Add Application management

### ISSUE THREAD

**Issue by Nonobis** [gauffininteractive/OneTrueError.Server#10]
Could add a screen to manage application ?
- Add / Modify / Delete
- Change Public / Private Key
- etc ....

**Comment by Nonobis** [comment]
found delete option in admin panel

**Comment by gauffininteractive** [comment]
So this issue is to regenerate a new key? (keep the old one X days to allow distributed applications to continue report errors during a transition period)

**Comment by Nonobis** [comment]
Not necessary, change application name could be a possibility.

Take exceptionless dashboard for example, there many interessing option you
could use on onetrue.

**Comment by gauffininteractive** [comment]
will do key management in a v1.1, requires that the old key is left for a while (until released applications have been updated). Name etc can now be changed in the admin
