### ISSUE TITLE
Report URL invalid in 'Updated' mail

### ISSUE THREAD

**Issue by jorrit** [gauffininteractive/OneTrueError.Server#20]
Whenever I receive an Updated notification, the Report URL ends with `/report/0`, creating an invalid URL.

**Comment by gauffininteractive** [comment]
corrected

**Comment by jorrit** [comment]
Thanks! Are you considering a new release?

**Comment by gauffininteractive** [comment]
1.0 will be released once the search have been implemented.

**Comment by gauffininteractive** [comment]
@jorrit  Just uploaded rc6. Will be released as v1.0 in a week if no bugs are found ;)

**Comment by jorrit** [comment]
Great!

**Comment by gauffininteractive** [comment]
have you tried rc6? Do it work for you?

**Comment by jorrit** [comment]
I have installed the update but the application using it has been crash free so far, unfortunately.

**Comment by jorrit** [comment]
It works, thanks!
