### ISSUE TITLE
Add REST (or the like) API support to create new application within OneTrueError

### ISSUE THREAD

**Issue by nzsmith1** [gauffininteractive/OneTrueError.Server#3]
This would allow a build server such as Jenkins to create an application and link it during build time.

**Comment by gauffininteractive** [comment]
There is a HTTP api which is used through ajax by the SPA library, the same API can be used for other things, like [creating an application](https://github.com/gauffininteractive/OneTrueError.Server/blob/master/src/Server/OneTrueError.Api/Core/Applications/Commands/CreateApplication.cs). What's missing through is a user independent authentication mechanism. 

Work to do:

* Create a way to create an API token in the administration area
* Add a custom authentication filter which checks for the API-token in a custom HTTP header
* Authenticate

**Comment by gauffininteractive** [comment]
Completed.

# Instructions

1. Download and compile the source code
2. Visit the admin area
3. Create a new ApiKey
4. Open your own project in VStudio
6. Reference `OneTrueError.Api.dll`
5. Reference `OneTrueError.Api.Client.dll`

Do something like this:

```csharp
var client = new OneTrueApiClient();
var uri = new Uri("http://yourServer/onetrueerror/");
client.Open(uri, "theApiKey", "sharedSecret");
var apps = await client.QueryAsync(new GetApplicationList());
```

You have the entire OneTrueError API at your disposal. 
It's documented here: http://onetrueerror.com/docs/api/server/html/N_OneTrueError_Api_Core.htm

(all namespaces starting with OneTrueError.Api)

**Comment by gauffininteractive** [comment]
Let us know what you think and we'll publish a nuget package for the server api client.

**Comment by nzsmith1** [comment]
Looks good so far, one small issue,
when trying to create a new API Key where I don't select an application, the text says that this is possible, but it would seem as if the code throws an error at this point, stack trace attached.
[apivalueError.txt.txt](https://github.com/gauffininteractive/OneTrueError.Server/files/498833/apivalueError.txt.txt)

Thanks so much for working on this request, it will be a fantastic help.

**Comment by gauffininteractive** [comment]
corrected that with the last commit

**Comment by nzsmith1** [comment]
Works great now.  Thanks!
