### ISSUE TITLE
New application is not accessible via Dashboard dropdown

### ISSUE THREAD

**Issue by marekpetak** [gauffininteractive/OneTrueError.Server#4]
Hi,

I'm running the server on Windows Server 2012 R2 64bit with SQL Server 2012.
using OneTrueError.Serrver-1.0-rc3

When I add new application via Create new application button in Dashboard dropdown, the overview changes to newly created Application, but after goind to Admin Area and back, I can no longer click on newly created application as it is not listed in drop down, although the name of newly created app is visible on X axis legend in the graph.

I do not have any exception data yet.
I can see new application being created in dbo.Applications table.

Is this intenttional, or just a bug?
![untitled](https://cloud.githubusercontent.com/assets/7045818/18543704/11a9eef6-7b29-11e6-8985-e47faf2324c3.png)

**Comment by jgauffin** [comment]
It's a bug. Does it help to logout and then login again?

**Comment by marekpetak** [comment]
yes. logging in/out helped ...

**Comment by gauffininteractive** [comment]
Corrected in the next commit.
